---
- hosts: managednode.example.com
  tasks:
  - name: File creation
    file: 
      path: /var/tmp/blah1128
      mode: "u=r,g=r,o=r"
      state: touch
  - name: Directory creation
    file:
      path: /var/tmp/dir1128
      mode: 4775
      state: directory
  - name: Link creation
    file: 
      src: /etc/hosts
      dest: /var/tmp/hosts
      owner: root
      group: root
      state: link
