---
- hosts: all
  tasks:
    - name: User creation with vars
      user: 
        name: "{{ item }}"
        state: present
      with_items:
        - sandeep
        - naidu
        - sandy
      register: endresult
    - name: debug info
      debug:
        var=endresult
    - local_action: copy content={{ endresult }} dest=/var/tmp/localusersonremotenode.out 
